// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mocks/handler.go -package=mocks .
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "booking-service/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenValidator is a mock of TokenValidator interface.
type MockTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenValidatorMockRecorder
	isgomock struct{}
}

// MockTokenValidatorMockRecorder is the mock recorder for MockTokenValidator.
type MockTokenValidatorMockRecorder struct {
	mock *MockTokenValidator
}

// NewMockTokenValidator creates a new mock instance.
func NewMockTokenValidator(ctrl *gomock.Controller) *MockTokenValidator {
	mock := &MockTokenValidator{ctrl: ctrl}
	mock.recorder = &MockTokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenValidator) EXPECT() *MockTokenValidatorMockRecorder {
	return m.recorder
}

// ValidateToken mocks base method.
func (m *MockTokenValidator) ValidateToken(ctx context.Context, tokenString string) (*models.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, tokenString)
	ret0, _ := ret[0].(*models.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenValidatorMockRecorder) ValidateToken(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenValidator)(nil).ValidateToken), ctx, tokenString)
}

// MockBookingService is a mock of BookingService interface.
type MockBookingService struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceMockRecorder
	isgomock struct{}
}

// MockBookingServiceMockRecorder is the mock recorder for MockBookingService.
type MockBookingServiceMockRecorder struct {
	mock *MockBookingService
}

// NewMockBookingService creates a new mock instance.
func NewMockBookingService(ctrl *gomock.Controller) *MockBookingService {
	mock := &MockBookingService{ctrl: ctrl}
	mock.recorder = &MockBookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingService) EXPECT() *MockBookingServiceMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockBookingService) Cancel(ctx context.Context, bookingID, userID uuid.UUID) (*models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, bookingID, userID)
	ret0, _ := ret[0].(*models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockBookingServiceMockRecorder) Cancel(ctx, bookingID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockBookingService)(nil).Cancel), ctx, bookingID, userID)
}

// Create mocks base method.
func (m *MockBookingService) Create(ctx context.Context, userID, slotID uuid.UUID) (*models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, slotID)
	ret0, _ := ret[0].(*models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBookingServiceMockRecorder) Create(ctx, userID, slotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookingService)(nil).Create), ctx, userID, slotID)
}

// GetByUserID mocks base method.
func (m *MockBookingService) GetByUserID(ctx context.Context, userID uuid.UUID) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockBookingServiceMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockBookingService)(nil).GetByUserID), ctx, userID)
}

// GetList mocks base method.
func (m *MockBookingService) GetList(ctx context.Context, pageSize, page uint64) (*models.BookingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, pageSize, page)
	ret0, _ := ret[0].(*models.BookingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockBookingServiceMockRecorder) GetList(ctx, pageSize, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockBookingService)(nil).GetList), ctx, pageSize, page)
}

// MockLaneService is a mock of LaneService interface.
type MockLaneService struct {
	ctrl     *gomock.Controller
	recorder *MockLaneServiceMockRecorder
	isgomock struct{}
}

// MockLaneServiceMockRecorder is the mock recorder for MockLaneService.
type MockLaneServiceMockRecorder struct {
	mock *MockLaneService
}

// NewMockLaneService creates a new mock instance.
func NewMockLaneService(ctrl *gomock.Controller) *MockLaneService {
	mock := &MockLaneService{ctrl: ctrl}
	mock.recorder = &MockLaneServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLaneService) EXPECT() *MockLaneServiceMockRecorder {
	return m.recorder
}

// CreateLane mocks base method.
func (m *MockLaneService) CreateLane(ctx context.Context, lCreate models.LaneCreate) (*models.Lane, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLane", ctx, lCreate)
	ret0, _ := ret[0].(*models.Lane)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLane indicates an expected call of CreateLane.
func (mr *MockLaneServiceMockRecorder) CreateLane(ctx, lCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLane", reflect.TypeOf((*MockLaneService)(nil).CreateLane), ctx, lCreate)
}

// CreateSchedule mocks base method.
func (m *MockLaneService) CreateSchedule(ctx context.Context, sch *models.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, sch)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockLaneServiceMockRecorder) CreateSchedule(ctx, sch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockLaneService)(nil).CreateSchedule), ctx, sch)
}

// GetAllLanes mocks base method.
func (m *MockLaneService) GetAllLanes(ctx context.Context) ([]models.Lane, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLanes", ctx)
	ret0, _ := ret[0].([]models.Lane)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLanes indicates an expected call of GetAllLanes.
func (mr *MockLaneServiceMockRecorder) GetAllLanes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLanes", reflect.TypeOf((*MockLaneService)(nil).GetAllLanes), ctx)
}

// GetAvailableSlots mocks base method.
func (m *MockLaneService) GetAvailableSlots(ctx context.Context, laneID uuid.UUID, date time.Time) ([]models.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSlots", ctx, laneID, date)
	ret0, _ := ret[0].([]models.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableSlots indicates an expected call of GetAvailableSlots.
func (mr *MockLaneServiceMockRecorder) GetAvailableSlots(ctx, laneID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSlots", reflect.TypeOf((*MockLaneService)(nil).GetAvailableSlots), ctx, laneID, date)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetOrCreateDummy mocks base method.
func (m *MockUserService) GetOrCreateDummy(ctx context.Context, role models.UserRole) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateDummy", ctx, role)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateDummy indicates an expected call of GetOrCreateDummy.
func (mr *MockUserServiceMockRecorder) GetOrCreateDummy(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateDummy", reflect.TypeOf((*MockUserService)(nil).GetOrCreateDummy), ctx, role)
}

// Login mocks base method.
func (m *MockUserService) Login(ctx context.Context, uLogin models.UserLogin) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, uLogin)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceMockRecorder) Login(ctx, uLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserService)(nil).Login), ctx, uLogin)
}

// Register mocks base method.
func (m *MockUserService) Register(ctx context.Context, uRegister models.UserRegister) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, uRegister)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceMockRecorder) Register(ctx, uRegister any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserService)(nil).Register), ctx, uRegister)
}

// MockTokenGenerator is a mock of TokenGenerator interface.
type MockTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockTokenGeneratorMockRecorder is the mock recorder for MockTokenGenerator.
type MockTokenGeneratorMockRecorder struct {
	mock *MockTokenGenerator
}

// NewMockTokenGenerator creates a new mock instance.
func NewMockTokenGenerator(ctrl *gomock.Controller) *MockTokenGenerator {
	mock := &MockTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenGenerator) EXPECT() *MockTokenGeneratorMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockTokenGenerator) GenerateToken(ctx context.Context, user *models.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockTokenGeneratorMockRecorder) GenerateToken(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTokenGenerator)(nil).GenerateToken), ctx, user)
}
