// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mocks/service.go -package=mocks .
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "booking-service/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache[K any, V any] struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder[K, V]
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder[K any, V any] struct {
	mock *MockCache[K, V]
}

// NewMockCache creates a new mock instance.
func NewMockCache[K any, V any](ctrl *gomock.Controller) *MockCache[K, V] {
	mock := &MockCache[K, V]{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder[K, V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache[K, V]) EXPECT() *MockCacheMockRecorder[K, V] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCache[K, V]) Delete(ctx context.Context, key K) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", ctx, key)
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheMockRecorder[K, V]) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCache[K, V])(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockCache[K, V]) Get(ctx context.Context, key K) (V, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder[K, V]) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache[K, V])(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockCache[K, V]) Set(ctx context.Context, key K, value V) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", ctx, key, value)
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder[K, V]) Set(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache[K, V])(nil).Set), ctx, key, value)
}

// MockSlotCahceInvalidator is a mock of SlotCahceInvalidator interface.
type MockSlotCahceInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockSlotCahceInvalidatorMockRecorder
	isgomock struct{}
}

// MockSlotCahceInvalidatorMockRecorder is the mock recorder for MockSlotCahceInvalidator.
type MockSlotCahceInvalidatorMockRecorder struct {
	mock *MockSlotCahceInvalidator
}

// NewMockSlotCahceInvalidator creates a new mock instance.
func NewMockSlotCahceInvalidator(ctrl *gomock.Controller) *MockSlotCahceInvalidator {
	mock := &MockSlotCahceInvalidator{ctrl: ctrl}
	mock.recorder = &MockSlotCahceInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotCahceInvalidator) EXPECT() *MockSlotCahceInvalidatorMockRecorder {
	return m.recorder
}

// InvalidateSlotsCache mocks base method.
func (m *MockSlotCahceInvalidator) InvalidateSlotsCache(ctx context.Context, roomID uuid.UUID, date time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateSlotsCache", ctx, roomID, date)
}

// InvalidateSlotsCache indicates an expected call of InvalidateSlotsCache.
func (mr *MockSlotCahceInvalidatorMockRecorder) InvalidateSlotsCache(ctx, roomID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateSlotsCache", reflect.TypeOf((*MockSlotCahceInvalidator)(nil).InvalidateSlotsCache), ctx, roomID, date)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetOrCreateForDummy mocks base method.
func (m *MockUserRepository) GetOrCreateForDummy(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateForDummy", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetOrCreateForDummy indicates an expected call of GetOrCreateForDummy.
func (mr *MockUserRepositoryMockRecorder) GetOrCreateForDummy(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateForDummy", reflect.TypeOf((*MockUserRepository)(nil).GetOrCreateForDummy), ctx, user)
}

// MockLaneRepository is a mock of LaneRepository interface.
type MockLaneRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLaneRepositoryMockRecorder
	isgomock struct{}
}

// MockLaneRepositoryMockRecorder is the mock recorder for MockLaneRepository.
type MockLaneRepositoryMockRecorder struct {
	mock *MockLaneRepository
}

// NewMockLaneRepository creates a new mock instance.
func NewMockLaneRepository(ctrl *gomock.Controller) *MockLaneRepository {
	mock := &MockLaneRepository{ctrl: ctrl}
	mock.recorder = &MockLaneRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLaneRepository) EXPECT() *MockLaneRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLaneRepository) Create(ctx context.Context, lane *models.Lane) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, lane)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLaneRepositoryMockRecorder) Create(ctx, lane any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLaneRepository)(nil).Create), ctx, lane)
}

// Get mocks base method.
func (m *MockLaneRepository) Get(ctx context.Context, id uuid.UUID) (*models.Lane, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.Lane)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLaneRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLaneRepository)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockLaneRepository) GetAll(ctx context.Context) ([]models.Lane, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.Lane)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockLaneRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLaneRepository)(nil).GetAll), ctx)
}

// MockScheduleRepository is a mock of ScheduleRepository interface.
type MockScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduleRepositoryMockRecorder is the mock recorder for MockScheduleRepository.
type MockScheduleRepositoryMockRecorder struct {
	mock *MockScheduleRepository
}

// NewMockScheduleRepository creates a new mock instance.
func NewMockScheduleRepository(ctrl *gomock.Controller) *MockScheduleRepository {
	mock := &MockScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepository) EXPECT() *MockScheduleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScheduleRepository) Create(ctx context.Context, s *models.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduleRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduleRepository)(nil).Create), ctx, s)
}

// GetByLaneID mocks base method.
func (m *MockScheduleRepository) GetByLaneID(ctx context.Context, laneID uuid.UUID) (*models.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLaneID", ctx, laneID)
	ret0, _ := ret[0].(*models.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLaneID indicates an expected call of GetByLaneID.
func (mr *MockScheduleRepositoryMockRecorder) GetByLaneID(ctx, laneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLaneID", reflect.TypeOf((*MockScheduleRepository)(nil).GetByLaneID), ctx, laneID)
}

// MockSlotRepository is a mock of SlotRepository interface.
type MockSlotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSlotRepositoryMockRecorder
	isgomock struct{}
}

// MockSlotRepositoryMockRecorder is the mock recorder for MockSlotRepository.
type MockSlotRepositoryMockRecorder struct {
	mock *MockSlotRepository
}

// NewMockSlotRepository creates a new mock instance.
func NewMockSlotRepository(ctrl *gomock.Controller) *MockSlotRepository {
	mock := &MockSlotRepository{ctrl: ctrl}
	mock.recorder = &MockSlotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotRepository) EXPECT() *MockSlotRepositoryMockRecorder {
	return m.recorder
}

// CreateSlots mocks base method.
func (m *MockSlotRepository) CreateSlots(ctx context.Context, slots []models.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSlots", ctx, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSlots indicates an expected call of CreateSlots.
func (mr *MockSlotRepositoryMockRecorder) CreateSlots(ctx, slots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSlots", reflect.TypeOf((*MockSlotRepository)(nil).CreateSlots), ctx, slots)
}

// GetAvailableByLaneAndDate mocks base method.
func (m *MockSlotRepository) GetAvailableByLaneAndDate(ctx context.Context, laneID uuid.UUID, date time.Time) ([]models.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableByLaneAndDate", ctx, laneID, date)
	ret0, _ := ret[0].([]models.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableByLaneAndDate indicates an expected call of GetAvailableByLaneAndDate.
func (mr *MockSlotRepositoryMockRecorder) GetAvailableByLaneAndDate(ctx, laneID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableByLaneAndDate", reflect.TypeOf((*MockSlotRepository)(nil).GetAvailableByLaneAndDate), ctx, laneID, date)
}

// GetByID mocks base method.
func (m *MockSlotRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSlotRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSlotRepository)(nil).GetByID), ctx, id)
}

// GetByLaneID mocks base method.
func (m *MockSlotRepository) GetByLaneID(ctx context.Context, laneID uuid.UUID) ([]models.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLaneID", ctx, laneID)
	ret0, _ := ret[0].([]models.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLaneID indicates an expected call of GetByLaneID.
func (mr *MockSlotRepositoryMockRecorder) GetByLaneID(ctx, laneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLaneID", reflect.TypeOf((*MockSlotRepository)(nil).GetByLaneID), ctx, laneID)
}

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockBookingRepository) Cancel(ctx context.Context, bookingID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, bookingID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockBookingRepositoryMockRecorder) Cancel(ctx, bookingID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockBookingRepository)(nil).Cancel), ctx, bookingID, userID)
}

// Create mocks base method.
func (m *MockBookingRepository) Create(ctx context.Context, b *models.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBookingRepositoryMockRecorder) Create(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookingRepository)(nil).Create), ctx, b)
}

// Get mocks base method.
func (m *MockBookingRepository) Get(ctx context.Context, bookingID uuid.UUID) (*models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, bookingID)
	ret0, _ := ret[0].(*models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBookingRepositoryMockRecorder) Get(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBookingRepository)(nil).Get), ctx, bookingID)
}

// GetActiveByUserID mocks base method.
func (m *MockBookingRepository) GetActiveByUserID(ctx context.Context, userID uuid.UUID) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByUserID indicates an expected call of GetActiveByUserID.
func (mr *MockBookingRepositoryMockRecorder) GetActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByUserID", reflect.TypeOf((*MockBookingRepository)(nil).GetActiveByUserID), ctx, userID)
}

// GetList mocks base method.
func (m *MockBookingRepository) GetList(ctx context.Context, limit, page uint64) (*models.BookingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, limit, page)
	ret0, _ := ret[0].(*models.BookingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockBookingRepositoryMockRecorder) GetList(ctx, limit, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockBookingRepository)(nil).GetList), ctx, limit, page)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTxManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTxManagerMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTxManager)(nil).Do), ctx, fn)
}
