// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BookingStatus.
const (
	Active    BookingStatus = "active"
	Cancelled BookingStatus = "cancelled"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Cancelled:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	BOOKINGNOTFOUND   ErrorResponseErrorCode = "BOOKING_NOT_FOUND"
	FORBIDDEN         ErrorResponseErrorCode = "FORBIDDEN"
	INTERNALERROR     ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDREQUEST    ErrorResponseErrorCode = "INVALID_REQUEST"
	LANENOTFOUND      ErrorResponseErrorCode = "LANE_NOT_FOUND"
	NOTFOUND          ErrorResponseErrorCode = "NOT_FOUND"
	SCHEDULEEXISTS    ErrorResponseErrorCode = "SCHEDULE_EXISTS"
	SLOTALREADYBOOKED ErrorResponseErrorCode = "SLOT_ALREADY_BOOKED"
	SLOTNOTFOUND      ErrorResponseErrorCode = "SLOT_NOT_FOUND"
	UNAUTHORIZED      ErrorResponseErrorCode = "UNAUTHORIZED"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case BOOKINGNOTFOUND:
		return true
	case FORBIDDEN:
		return true
	case INTERNALERROR:
		return true
	case INVALIDREQUEST:
		return true
	case LANENOTFOUND:
		return true
	case NOTFOUND:
		return true
	case SCHEDULEEXISTS:
		return true
	case SLOTALREADYBOOKED:
		return true
	case SLOTNOTFOUND:
		return true
	case UNAUTHORIZED:
		return true
	default:
		return false
	}
}

// Defines values for LaneType.
const (
	LaneTypeKids     LaneType = "kids"
	LaneTypePro      LaneType = "pro"
	LaneTypeStandard LaneType = "standard"
	LaneTypeVip      LaneType = "vip"
)

// Valid indicates whether the value is a known member of the LaneType enum.
func (e LaneType) Valid() bool {
	switch e {
	case LaneTypeKids:
		return true
	case LaneTypePro:
		return true
	case LaneTypeStandard:
		return true
	case LaneTypeVip:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for PostDummyLoginJSONBodyRole.
const (
	PostDummyLoginJSONBodyRoleAdmin PostDummyLoginJSONBodyRole = "admin"
	PostDummyLoginJSONBodyRoleUser  PostDummyLoginJSONBodyRole = "user"
)

// Valid indicates whether the value is a known member of the PostDummyLoginJSONBodyRole enum.
func (e PostDummyLoginJSONBodyRole) Valid() bool {
	switch e {
	case PostDummyLoginJSONBodyRoleAdmin:
		return true
	case PostDummyLoginJSONBodyRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for PostLanesCreateJSONBodyType.
const (
	PostLanesCreateJSONBodyTypeKids     PostLanesCreateJSONBodyType = "kids"
	PostLanesCreateJSONBodyTypePro      PostLanesCreateJSONBodyType = "pro"
	PostLanesCreateJSONBodyTypeStandard PostLanesCreateJSONBodyType = "standard"
	PostLanesCreateJSONBodyTypeVip      PostLanesCreateJSONBodyType = "vip"
)

// Valid indicates whether the value is a known member of the PostLanesCreateJSONBodyType enum.
func (e PostLanesCreateJSONBodyType) Valid() bool {
	switch e {
	case PostLanesCreateJSONBodyTypeKids:
		return true
	case PostLanesCreateJSONBodyTypePro:
		return true
	case PostLanesCreateJSONBodyTypeStandard:
		return true
	case PostLanesCreateJSONBodyTypeVip:
		return true
	default:
		return false
	}
}

// Defines values for PostRegisterJSONBodyRole.
const (
	PostRegisterJSONBodyRoleAdmin PostRegisterJSONBodyRole = "admin"
	PostRegisterJSONBodyRoleUser  PostRegisterJSONBodyRole = "user"
)

// Valid indicates whether the value is a known member of the PostRegisterJSONBodyRole enum.
func (e PostRegisterJSONBodyRole) Valid() bool {
	switch e {
	case PostRegisterJSONBodyRoleAdmin:
		return true
	case PostRegisterJSONBodyRoleUser:
		return true
	default:
		return false
	}
}

// Booking defines model for Booking.
type Booking struct {
	ConferenceLink *string            `json:"conferenceLink,omitempty"`
	CreatedAt      *time.Time         `json:"createdAt,omitempty"`
	Id             openapi_types.UUID `json:"id"`
	SlotId         openapi_types.UUID `json:"slotId"`
	Status         BookingStatus      `json:"status"`
	UserId         openapi_types.UUID `json:"userId"`
}

// BookingStatus defines model for Booking.Status.
type BookingStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// InternalErrorResponse defines model for InternalErrorResponse.
type InternalErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Lane defines model for Lane.
type Lane struct {
	CreatedAt   *time.Time         `json:"createdAt,omitempty"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	IsActive    *bool              `json:"is_active,omitempty"`
	Name        string             `json:"name"`
	Type        *LaneType          `json:"type"`
}

// LaneType defines model for Lane.Type.
type LaneType string

// Pagination defines model for Pagination.
type Pagination struct {
	// Page Текущая страница (начиная с 1)
	Page int `json:"page"`

	// PageSize Размер страницы
	PageSize int `json:"pageSize"`

	// Total Общее количество записей
	Total int `json:"total"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	// DaysOfWeek 1=Пн .. 7=Вс, дни доступности. Каждое значение должно быть в диапазоне 1–7.
	DaysOfWeek []int `json:"daysOfWeek"`

	// EndTime Время окончания (HH:MM) в рамках дня. Интерпретируется как UTC.
	EndTime string              `json:"endTime"`
	Id      *openapi_types.UUID `json:"id,omitempty"`
	LaneId  openapi_types.UUID  `json:"laneId"`

	// StartTime Время начала (HH:MM) в рамках дня. Интерпретируется как UTC.
	StartTime string `json:"startTime"`
}

// Slot defines model for Slot.
type Slot struct {
	// End Время окончания слота в UTC (ISO 8601, например 2024-06-10T09:30:00Z)
	End    time.Time          `json:"end"`
	Id     openapi_types.UUID `json:"id"`
	LaneId openapi_types.UUID `json:"laneId"`

	// Start Время начала слота в UTC (ISO 8601, например 2024-06-10T09:00:00Z)
	Start time.Time `json:"start"`
}

// Token defines model for Token.
type Token struct {
	// Token JWT для заголовка Authorization Bearer
	Token string `json:"token"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Role      UserRole            `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// BookingIdPath defines model for BookingIdPath.
type BookingIdPath = openapi_types.UUID

// LaneIdPath defines model for LaneIdPath.
type LaneIdPath = openapi_types.UUID

// PostBookingsCreateJSONBody defines parameters for PostBookingsCreate.
type PostBookingsCreateJSONBody struct {
	CreateConferenceLink *bool              `json:"createConferenceLink,omitempty"`
	SlotId               openapi_types.UUID `json:"slotId"`
}

// GetBookingsListParams defines parameters for GetBookingsList.
type GetBookingsListParams struct {
	// Page Номер страницы (начиная с 1). По умолчанию 1.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Количество записей на странице. По умолчанию 20, максимум 100.
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostDummyLoginJSONBody defines parameters for PostDummyLogin.
type PostDummyLoginJSONBody struct {
	Role PostDummyLoginJSONBodyRole `json:"role"`
}

// PostDummyLoginJSONBodyRole defines parameters for PostDummyLogin.
type PostDummyLoginJSONBodyRole string

// PostLanesCreateJSONBody defines parameters for PostLanesCreate.
type PostLanesCreateJSONBody struct {
	Description *string                     `json:"description,omitempty"`
	Name        string                      `json:"name"`
	Type        PostLanesCreateJSONBodyType `json:"type"`
}

// PostLanesCreateJSONBodyType defines parameters for PostLanesCreate.
type PostLanesCreateJSONBodyType string

// GetLanesLaneIdSlotsListParams defines parameters for GetLanesLaneIdSlotsList.
type GetLanesLaneIdSlotsListParams struct {
	// Date Дата в формате ISO 8601 (например: 2024-06-10). Обязательный параметр; при отсутствии — 400.
	Date openapi_types.Date `form:"date" json:"date"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PostRegisterJSONBody defines parameters for PostRegister.
type PostRegisterJSONBody struct {
	Email    openapi_types.Email      `json:"email"`
	Password string                   `json:"password"`
	Role     PostRegisterJSONBodyRole `json:"role"`
}

// PostRegisterJSONBodyRole defines parameters for PostRegister.
type PostRegisterJSONBodyRole string

// PostBookingsCreateJSONRequestBody defines body for PostBookingsCreate for application/json ContentType.
type PostBookingsCreateJSONRequestBody PostBookingsCreateJSONBody

// PostDummyLoginJSONRequestBody defines body for PostDummyLogin for application/json ContentType.
type PostDummyLoginJSONRequestBody PostDummyLoginJSONBody

// PostLanesCreateJSONRequestBody defines body for PostLanesCreate for application/json ContentType.
type PostLanesCreateJSONRequestBody PostLanesCreateJSONBody

// PostLanesLaneIdScheduleCreateJSONRequestBody defines body for PostLanesLaneIdScheduleCreate for application/json ContentType.
type PostLanesLaneIdScheduleCreateJSONRequestBody = Schedule

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody PostRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать бронь на слот (только user). Опционально — запросить ссылку на конференцию.
	// (POST /bookings/create)
	PostBookingsCreate(ctx echo.Context) error
	// Список всех броней с пагинацией (только admin)
	// (GET /bookings/list)
	GetBookingsList(ctx echo.Context, params GetBookingsListParams) error
	// Список броней текущего пользователя (только user)
	// (GET /bookings/my)
	GetBookingsMy(ctx echo.Context) error
	// Отменить бронь (только своя бронь, только user)
	// (POST /bookings/{bookingId}/cancel)
	PostBookingsBookingIdCancel(ctx echo.Context, bookingId BookingIdPath) error
	// Получить тестовый JWT по роли (ОБЯЗАТЕЛЬНО). Доступен без авторизации.
	// (POST /dummyLogin)
	PostDummyLogin(ctx echo.Context) error
	// Создать дорожку (только admin)
	// (POST /lanes/create)
	PostLanesCreate(ctx echo.Context) error
	// Список дорожек (admin и user)
	// (GET /lanes/list)
	GetLanesList(ctx echo.Context) error
	// Создать расписание дорожки (только admin, только один раз). Длительность слота 30 мин. После создания расписание изменить нельзя.
	// (POST /lanes/{laneId}/schedule/create)
	PostLanesLaneIdScheduleCreate(ctx echo.Context, laneId LaneIdPath) error
	// Список доступных для бронирования слотов по дорожке и дате (admin и user). Наиболее нагруженный эндпоинт.
	// (GET /lanes/{laneId}/slots/list)
	GetLanesLaneIdSlotsList(ctx echo.Context, laneId LaneIdPath, params GetLanesLaneIdSlotsListParams) error
	// Авторизация по email и паролю (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
	// (POST /login)
	PostLogin(ctx echo.Context) error
	// Регистрация пользователя (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
	// (POST /register)
	PostRegister(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostBookingsCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostBookingsCreate(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBookingsCreate(ctx)
	return err
}

// GetBookingsList converts echo context to params.
func (w *ServerInterfaceWrapper) GetBookingsList(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBookingsListParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", ctx.QueryParams(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageSize: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBookingsList(ctx, params)
	return err
}

// GetBookingsMy converts echo context to params.
func (w *ServerInterfaceWrapper) GetBookingsMy(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBookingsMy(ctx)
	return err
}

// PostBookingsBookingIdCancel converts echo context to params.
func (w *ServerInterfaceWrapper) PostBookingsBookingIdCancel(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "bookingId" -------------
	var bookingId BookingIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "bookingId", ctx.Param("bookingId"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter bookingId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBookingsBookingIdCancel(ctx, bookingId)
	return err
}

// PostDummyLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostDummyLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDummyLogin(ctx)
	return err
}

// PostLanesCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostLanesCreate(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLanesCreate(ctx)
	return err
}

// GetLanesList converts echo context to params.
func (w *ServerInterfaceWrapper) GetLanesList(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLanesList(ctx)
	return err
}

// PostLanesLaneIdScheduleCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostLanesLaneIdScheduleCreate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "laneId" -------------
	var laneId LaneIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "laneId", ctx.Param("laneId"), &laneId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter laneId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLanesLaneIdScheduleCreate(ctx, laneId)
	return err
}

// GetLanesLaneIdSlotsList converts echo context to params.
func (w *ServerInterfaceWrapper) GetLanesLaneIdSlotsList(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "laneId" -------------
	var laneId LaneIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "laneId", ctx.Param("laneId"), &laneId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter laneId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLanesLaneIdSlotsListParams
	// ------------- Required query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", ctx.QueryParams(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLanesLaneIdSlotsList(ctx, laneId, params)
	return err
}

// PostLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLogin(ctx)
	return err
}

// PostRegister converts echo context to params.
func (w *ServerInterfaceWrapper) PostRegister(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostRegister(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/bookings/create", wrapper.PostBookingsCreate)
	router.GET(baseURL+"/bookings/list", wrapper.GetBookingsList)
	router.GET(baseURL+"/bookings/my", wrapper.GetBookingsMy)
	router.POST(baseURL+"/bookings/:bookingId/cancel", wrapper.PostBookingsBookingIdCancel)
	router.POST(baseURL+"/dummyLogin", wrapper.PostDummyLogin)
	router.POST(baseURL+"/lanes/create", wrapper.PostLanesCreate)
	router.GET(baseURL+"/lanes/list", wrapper.GetLanesList)
	router.POST(baseURL+"/lanes/:laneId/schedule/create", wrapper.PostLanesLaneIdScheduleCreate)
	router.GET(baseURL+"/lanes/:laneId/slots/list", wrapper.GetLanesLaneIdSlotsList)
	router.POST(baseURL+"/login", wrapper.PostLogin)
	router.POST(baseURL+"/register", wrapper.PostRegister)

}

type PostBookingsCreateRequestObject struct {
	Body *PostBookingsCreateJSONRequestBody
}

type PostBookingsCreateResponseObject interface {
	VisitPostBookingsCreateResponse(w http.ResponseWriter) error
}

type PostBookingsCreate201JSONResponse struct {
	Booking *Booking `json:"booking,omitempty"`
}

func (response PostBookingsCreate201JSONResponse) VisitPostBookingsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsCreate400JSONResponse ErrorResponse

func (response PostBookingsCreate400JSONResponse) VisitPostBookingsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsCreate401JSONResponse ErrorResponse

func (response PostBookingsCreate401JSONResponse) VisitPostBookingsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsCreate403JSONResponse ErrorResponse

func (response PostBookingsCreate403JSONResponse) VisitPostBookingsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsCreate404JSONResponse ErrorResponse

func (response PostBookingsCreate404JSONResponse) VisitPostBookingsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsCreate409JSONResponse ErrorResponse

func (response PostBookingsCreate409JSONResponse) VisitPostBookingsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsCreate500JSONResponse InternalErrorResponse

func (response PostBookingsCreate500JSONResponse) VisitPostBookingsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetBookingsListRequestObject struct {
	Params GetBookingsListParams
}

type GetBookingsListResponseObject interface {
	VisitGetBookingsListResponse(w http.ResponseWriter) error
}

type GetBookingsList200JSONResponse struct {
	Bookings   *[]Booking  `json:"bookings,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

func (response GetBookingsList200JSONResponse) VisitGetBookingsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBookingsList400JSONResponse ErrorResponse

func (response GetBookingsList400JSONResponse) VisitGetBookingsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetBookingsList401JSONResponse ErrorResponse

func (response GetBookingsList401JSONResponse) VisitGetBookingsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetBookingsList403JSONResponse ErrorResponse

func (response GetBookingsList403JSONResponse) VisitGetBookingsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetBookingsList500JSONResponse InternalErrorResponse

func (response GetBookingsList500JSONResponse) VisitGetBookingsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetBookingsMyRequestObject struct {
}

type GetBookingsMyResponseObject interface {
	VisitGetBookingsMyResponse(w http.ResponseWriter) error
}

type GetBookingsMy200JSONResponse struct {
	Bookings *[]Booking `json:"bookings,omitempty"`
}

func (response GetBookingsMy200JSONResponse) VisitGetBookingsMyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBookingsMy401JSONResponse ErrorResponse

func (response GetBookingsMy401JSONResponse) VisitGetBookingsMyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetBookingsMy403JSONResponse ErrorResponse

func (response GetBookingsMy403JSONResponse) VisitGetBookingsMyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetBookingsMy500JSONResponse InternalErrorResponse

func (response GetBookingsMy500JSONResponse) VisitGetBookingsMyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsBookingIdCancelRequestObject struct {
	BookingId BookingIdPath `json:"bookingId"`
}

type PostBookingsBookingIdCancelResponseObject interface {
	VisitPostBookingsBookingIdCancelResponse(w http.ResponseWriter) error
}

type PostBookingsBookingIdCancel200JSONResponse struct {
	Booking *Booking `json:"booking,omitempty"`
}

func (response PostBookingsBookingIdCancel200JSONResponse) VisitPostBookingsBookingIdCancelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsBookingIdCancel401JSONResponse ErrorResponse

func (response PostBookingsBookingIdCancel401JSONResponse) VisitPostBookingsBookingIdCancelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsBookingIdCancel403JSONResponse ErrorResponse

func (response PostBookingsBookingIdCancel403JSONResponse) VisitPostBookingsBookingIdCancelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsBookingIdCancel404JSONResponse ErrorResponse

func (response PostBookingsBookingIdCancel404JSONResponse) VisitPostBookingsBookingIdCancelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostBookingsBookingIdCancel500JSONResponse InternalErrorResponse

func (response PostBookingsBookingIdCancel500JSONResponse) VisitPostBookingsBookingIdCancelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostDummyLoginRequestObject struct {
	Body *PostDummyLoginJSONRequestBody
}

type PostDummyLoginResponseObject interface {
	VisitPostDummyLoginResponse(w http.ResponseWriter) error
}

type PostDummyLogin200JSONResponse Token

func (response PostDummyLogin200JSONResponse) VisitPostDummyLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostDummyLogin400JSONResponse ErrorResponse

func (response PostDummyLogin400JSONResponse) VisitPostDummyLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostDummyLogin500JSONResponse InternalErrorResponse

func (response PostDummyLogin500JSONResponse) VisitPostDummyLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesCreateRequestObject struct {
	Body *PostLanesCreateJSONRequestBody
}

type PostLanesCreateResponseObject interface {
	VisitPostLanesCreateResponse(w http.ResponseWriter) error
}

type PostLanesCreate201JSONResponse struct {
	Lane *Lane `json:"lane,omitempty"`
}

func (response PostLanesCreate201JSONResponse) VisitPostLanesCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesCreate400JSONResponse ErrorResponse

func (response PostLanesCreate400JSONResponse) VisitPostLanesCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesCreate401JSONResponse ErrorResponse

func (response PostLanesCreate401JSONResponse) VisitPostLanesCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesCreate403JSONResponse ErrorResponse

func (response PostLanesCreate403JSONResponse) VisitPostLanesCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesCreate500JSONResponse InternalErrorResponse

func (response PostLanesCreate500JSONResponse) VisitPostLanesCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetLanesListRequestObject struct {
}

type GetLanesListResponseObject interface {
	VisitGetLanesListResponse(w http.ResponseWriter) error
}

type GetLanesList200JSONResponse struct {
	Lanes *[]Lane `json:"lanes,omitempty"`
}

func (response GetLanesList200JSONResponse) VisitGetLanesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLanesList401JSONResponse ErrorResponse

func (response GetLanesList401JSONResponse) VisitGetLanesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetLanesList500JSONResponse InternalErrorResponse

func (response GetLanesList500JSONResponse) VisitGetLanesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesLaneIdScheduleCreateRequestObject struct {
	LaneId LaneIdPath `json:"laneId"`
	Body   *PostLanesLaneIdScheduleCreateJSONRequestBody
}

type PostLanesLaneIdScheduleCreateResponseObject interface {
	VisitPostLanesLaneIdScheduleCreateResponse(w http.ResponseWriter) error
}

type PostLanesLaneIdScheduleCreate201JSONResponse struct {
	Schedule *Schedule `json:"schedule,omitempty"`
}

func (response PostLanesLaneIdScheduleCreate201JSONResponse) VisitPostLanesLaneIdScheduleCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesLaneIdScheduleCreate400JSONResponse ErrorResponse

func (response PostLanesLaneIdScheduleCreate400JSONResponse) VisitPostLanesLaneIdScheduleCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesLaneIdScheduleCreate401JSONResponse ErrorResponse

func (response PostLanesLaneIdScheduleCreate401JSONResponse) VisitPostLanesLaneIdScheduleCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesLaneIdScheduleCreate403JSONResponse ErrorResponse

func (response PostLanesLaneIdScheduleCreate403JSONResponse) VisitPostLanesLaneIdScheduleCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesLaneIdScheduleCreate404JSONResponse ErrorResponse

func (response PostLanesLaneIdScheduleCreate404JSONResponse) VisitPostLanesLaneIdScheduleCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesLaneIdScheduleCreate409JSONResponse ErrorResponse

func (response PostLanesLaneIdScheduleCreate409JSONResponse) VisitPostLanesLaneIdScheduleCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostLanesLaneIdScheduleCreate500JSONResponse InternalErrorResponse

func (response PostLanesLaneIdScheduleCreate500JSONResponse) VisitPostLanesLaneIdScheduleCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetLanesLaneIdSlotsListRequestObject struct {
	LaneId LaneIdPath `json:"laneId"`
	Params GetLanesLaneIdSlotsListParams
}

type GetLanesLaneIdSlotsListResponseObject interface {
	VisitGetLanesLaneIdSlotsListResponse(w http.ResponseWriter) error
}

type GetLanesLaneIdSlotsList200JSONResponse struct {
	Slots *[]Slot `json:"slots,omitempty"`
}

func (response GetLanesLaneIdSlotsList200JSONResponse) VisitGetLanesLaneIdSlotsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLanesLaneIdSlotsList400JSONResponse ErrorResponse

func (response GetLanesLaneIdSlotsList400JSONResponse) VisitGetLanesLaneIdSlotsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetLanesLaneIdSlotsList401JSONResponse ErrorResponse

func (response GetLanesLaneIdSlotsList401JSONResponse) VisitGetLanesLaneIdSlotsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetLanesLaneIdSlotsList404JSONResponse ErrorResponse

func (response GetLanesLaneIdSlotsList404JSONResponse) VisitGetLanesLaneIdSlotsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetLanesLaneIdSlotsList500JSONResponse InternalErrorResponse

func (response GetLanesLaneIdSlotsList500JSONResponse) VisitGetLanesLaneIdSlotsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginRequestObject struct {
	Body *PostLoginJSONRequestBody
}

type PostLoginResponseObject interface {
	VisitPostLoginResponse(w http.ResponseWriter) error
}

type PostLogin200JSONResponse Token

func (response PostLogin200JSONResponse) VisitPostLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostLogin401JSONResponse ErrorResponse

func (response PostLogin401JSONResponse) VisitPostLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostLogin500JSONResponse InternalErrorResponse

func (response PostLogin500JSONResponse) VisitPostLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostRegisterRequestObject struct {
	Body *PostRegisterJSONRequestBody
}

type PostRegisterResponseObject interface {
	VisitPostRegisterResponse(w http.ResponseWriter) error
}

type PostRegister201JSONResponse struct {
	User *User `json:"user,omitempty"`
}

func (response PostRegister201JSONResponse) VisitPostRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostRegister400JSONResponse ErrorResponse

func (response PostRegister400JSONResponse) VisitPostRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostRegister500JSONResponse InternalErrorResponse

func (response PostRegister500JSONResponse) VisitPostRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Создать бронь на слот (только user). Опционально — запросить ссылку на конференцию.
	// (POST /bookings/create)
	PostBookingsCreate(ctx context.Context, request PostBookingsCreateRequestObject) (PostBookingsCreateResponseObject, error)
	// Список всех броней с пагинацией (только admin)
	// (GET /bookings/list)
	GetBookingsList(ctx context.Context, request GetBookingsListRequestObject) (GetBookingsListResponseObject, error)
	// Список броней текущего пользователя (только user)
	// (GET /bookings/my)
	GetBookingsMy(ctx context.Context, request GetBookingsMyRequestObject) (GetBookingsMyResponseObject, error)
	// Отменить бронь (только своя бронь, только user)
	// (POST /bookings/{bookingId}/cancel)
	PostBookingsBookingIdCancel(ctx context.Context, request PostBookingsBookingIdCancelRequestObject) (PostBookingsBookingIdCancelResponseObject, error)
	// Получить тестовый JWT по роли (ОБЯЗАТЕЛЬНО). Доступен без авторизации.
	// (POST /dummyLogin)
	PostDummyLogin(ctx context.Context, request PostDummyLoginRequestObject) (PostDummyLoginResponseObject, error)
	// Создать дорожку (только admin)
	// (POST /lanes/create)
	PostLanesCreate(ctx context.Context, request PostLanesCreateRequestObject) (PostLanesCreateResponseObject, error)
	// Список дорожек (admin и user)
	// (GET /lanes/list)
	GetLanesList(ctx context.Context, request GetLanesListRequestObject) (GetLanesListResponseObject, error)
	// Создать расписание дорожки (только admin, только один раз). Длительность слота 30 мин. После создания расписание изменить нельзя.
	// (POST /lanes/{laneId}/schedule/create)
	PostLanesLaneIdScheduleCreate(ctx context.Context, request PostLanesLaneIdScheduleCreateRequestObject) (PostLanesLaneIdScheduleCreateResponseObject, error)
	// Список доступных для бронирования слотов по дорожке и дате (admin и user). Наиболее нагруженный эндпоинт.
	// (GET /lanes/{laneId}/slots/list)
	GetLanesLaneIdSlotsList(ctx context.Context, request GetLanesLaneIdSlotsListRequestObject) (GetLanesLaneIdSlotsListResponseObject, error)
	// Авторизация по email и паролю (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
	// (POST /login)
	PostLogin(ctx context.Context, request PostLoginRequestObject) (PostLoginResponseObject, error)
	// Регистрация пользователя (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
	// (POST /register)
	PostRegister(ctx context.Context, request PostRegisterRequestObject) (PostRegisterResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostBookingsCreate operation middleware
func (sh *strictHandler) PostBookingsCreate(ctx echo.Context) error {
	var request PostBookingsCreateRequestObject

	var body PostBookingsCreateJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostBookingsCreate(ctx.Request().Context(), request.(PostBookingsCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostBookingsCreate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostBookingsCreateResponseObject); ok {
		return validResponse.VisitPostBookingsCreateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBookingsList operation middleware
func (sh *strictHandler) GetBookingsList(ctx echo.Context, params GetBookingsListParams) error {
	var request GetBookingsListRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBookingsList(ctx.Request().Context(), request.(GetBookingsListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBookingsList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBookingsListResponseObject); ok {
		return validResponse.VisitGetBookingsListResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBookingsMy operation middleware
func (sh *strictHandler) GetBookingsMy(ctx echo.Context) error {
	var request GetBookingsMyRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBookingsMy(ctx.Request().Context(), request.(GetBookingsMyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBookingsMy")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBookingsMyResponseObject); ok {
		return validResponse.VisitGetBookingsMyResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostBookingsBookingIdCancel operation middleware
func (sh *strictHandler) PostBookingsBookingIdCancel(ctx echo.Context, bookingId BookingIdPath) error {
	var request PostBookingsBookingIdCancelRequestObject

	request.BookingId = bookingId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostBookingsBookingIdCancel(ctx.Request().Context(), request.(PostBookingsBookingIdCancelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostBookingsBookingIdCancel")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostBookingsBookingIdCancelResponseObject); ok {
		return validResponse.VisitPostBookingsBookingIdCancelResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostDummyLogin operation middleware
func (sh *strictHandler) PostDummyLogin(ctx echo.Context) error {
	var request PostDummyLoginRequestObject

	var body PostDummyLoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostDummyLogin(ctx.Request().Context(), request.(PostDummyLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDummyLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostDummyLoginResponseObject); ok {
		return validResponse.VisitPostDummyLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostLanesCreate operation middleware
func (sh *strictHandler) PostLanesCreate(ctx echo.Context) error {
	var request PostLanesCreateRequestObject

	var body PostLanesCreateJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostLanesCreate(ctx.Request().Context(), request.(PostLanesCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLanesCreate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostLanesCreateResponseObject); ok {
		return validResponse.VisitPostLanesCreateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetLanesList operation middleware
func (sh *strictHandler) GetLanesList(ctx echo.Context) error {
	var request GetLanesListRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLanesList(ctx.Request().Context(), request.(GetLanesListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLanesList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLanesListResponseObject); ok {
		return validResponse.VisitGetLanesListResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostLanesLaneIdScheduleCreate operation middleware
func (sh *strictHandler) PostLanesLaneIdScheduleCreate(ctx echo.Context, laneId LaneIdPath) error {
	var request PostLanesLaneIdScheduleCreateRequestObject

	request.LaneId = laneId

	var body PostLanesLaneIdScheduleCreateJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostLanesLaneIdScheduleCreate(ctx.Request().Context(), request.(PostLanesLaneIdScheduleCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLanesLaneIdScheduleCreate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostLanesLaneIdScheduleCreateResponseObject); ok {
		return validResponse.VisitPostLanesLaneIdScheduleCreateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetLanesLaneIdSlotsList operation middleware
func (sh *strictHandler) GetLanesLaneIdSlotsList(ctx echo.Context, laneId LaneIdPath, params GetLanesLaneIdSlotsListParams) error {
	var request GetLanesLaneIdSlotsListRequestObject

	request.LaneId = laneId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLanesLaneIdSlotsList(ctx.Request().Context(), request.(GetLanesLaneIdSlotsListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLanesLaneIdSlotsList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLanesLaneIdSlotsListResponseObject); ok {
		return validResponse.VisitGetLanesLaneIdSlotsListResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostLogin operation middleware
func (sh *strictHandler) PostLogin(ctx echo.Context) error {
	var request PostLoginRequestObject

	var body PostLoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostLogin(ctx.Request().Context(), request.(PostLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostLoginResponseObject); ok {
		return validResponse.VisitPostLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostRegister operation middleware
func (sh *strictHandler) PostRegister(ctx echo.Context) error {
	var request PostRegisterRequestObject

	var body PostRegisterJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostRegister(ctx.Request().Context(), request.(PostRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRegister")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostRegisterResponseObject); ok {
		return validResponse.VisitPostRegisterResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
